version: '3'
services:
  app:
    container_name: my_app_express
    restart: always
    build: .
    ports:
    - '80:8000'
    links:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
    - '6379:6379'
